name: office_management_mobile
description: "Office Management mobile app using the Flask REST API."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.14.1
  provider: ^6.1.5+1
  dio: ^5.11.0
  flutter_secure_storage: ^11.0.0
  fl_chart: ^1.2.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  pdf: ^3.11.3
  printing: ^5.14.2
  image_picker: ^1.2.3
  excel: ^4.0.6
  public_file_saver: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ilogictech_logo.jpeg
    - assets/ilogictech_icon.png
